export const DELETE_ITEM = 'DELETE_ITEM';
export const TOGGLE_FORM_TODO = 'TOGGLE_FORM_TODO';
export const TOGGLE_FORM_GOALS = 'TOGGLE_FORM_GOALS';
export const UPDATE_TIME = 'UPDATE_TIME';
export const TOGGLE_SWITCH = 'TOGGLE_SWITCH';
